
#---
spring:
    profiles:
      active: 
      - d
---
server:
    port: 10021
spring:
    profiles: d   #开发环境
    application:
      name: cf-s-d-10021      
---
server:
    port: 10022
spring:
    profiles: t   #测试环境
    application:
      name: cf-s-d-10022
